import Image from "next/image";
import {
  Activity,
  Bot,
  Check,
  Database,
  GitPullRequest,
  Globe,
  Library,
  MousePointer2,
  RefreshCw,
  Server,
  Workflow,
  type LucideIcon,
} from "lucide-react";
import { PMMark } from "@/components/site/logo";
import { cn } from "@/lib/utils";

/**
 * Hero illustration (DA v3, after dust.tt's isometric floor): four extruded platforms generated by
 * `scripts/gen-hero-iso.py` (backend = blue, applied AI = pink, frontend = lime, DevOps = sky),
 * inhabited by icon chips, plus a floating "what I'm shipping" card. Anchors are the % printed by
 * the generator: re-run it and copy them here if the scene changes.
 */
const RATIO = "1059.2 / 660";

type Chip = { left: number; top: number; icon?: LucideIcon; status?: "green" | "blue"; label: string };

const CHIPS: Chip[] = [
  { left: 57.8, top: 58.5, icon: Server, status: "green", label: "APIs" },
  { left: 37.2, top: 57.6, icon: Database, status: "blue", label: "Data" },
  { left: 42.2, top: 27.6, icon: Globe, status: "green", label: "Web" },
  { left: 44.1, top: 33.9, icon: MousePointer2, label: "UI" },
  { left: 74.5, top: 47.6, icon: Bot, status: "green", label: "Agents" },
  { left: 75.5, top: 57.6, icon: Library, status: "blue", label: "Retrieval" },
  { left: 23.0, top: 48.0, icon: Workflow, status: "green", label: "CI/CD" },
  { left: 21.1, top: 55.3, icon: Activity, label: "Observability" },
  { left: 46.1, top: 78.5, icon: GitPullRequest, status: "blue", label: "Pull request" },
];
const PIERRE = { left: 47.1, top: 48.5 };
const CORTEX = { left: 68.2, top: 58.0 };

const dot = { green: "bg-shape-green", blue: "bg-shape-blue" } as const;

function IconChip({ chip }: { chip: Chip }) {
  const Icon = chip.icon!;
  return (
    <span
      className="absolute grid size-8 -translate-x-1/2 -translate-y-[85%] place-items-center rounded-full bg-card text-foreground/80 shadow-md ring-1 ring-foreground/5 sm:size-9"
      style={{ left: `${chip.left}%`, top: `${chip.top}%` }}
      title={chip.label}
    >
      <Icon className="size-3.5 sm:size-4" strokeWidth={1.75} />
      {chip.status ? (
        <span className={cn("absolute -bottom-0.5 -right-0.5 size-2.5 rounded-full ring-2 ring-card", dot[chip.status])} />
      ) : null}
    </span>
  );
}

const SHIPPING = [
  { name: "Taskforce", what: "AI delivery OS", status: "Live", tone: "green" },
  { name: "Brain OS", what: "reference memory", status: "R&D", tone: "blue" },
  { name: "Plania", what: "13k-user SaaS", status: "Leading", tone: "yellow" },
  { name: "Safex", what: "AI sales agent", status: "In production", tone: "green" },
] as const;

const statusStyle = {
  green: "bg-tint-green text-ink-green",
  blue: "bg-tint-blue text-ink-blue",
  yellow: "bg-tint-yellow text-ink-yellow",
} as const;

function ShippingCard({ className }: { className?: string }) {
  return (
    <div className={cn("w-[21rem] rounded-2xl border bg-card/95 p-4 text-left shadow-xl backdrop-blur-sm", className)}>
      <div className="flex items-center gap-3">
        <span className="grid size-9 place-items-center rounded-full border bg-paper-soft">
          <PMMark className="h-3" />
        </span>
        <div className="leading-tight">
          <p className="text-sm font-semibold tracking-[-0.01em]">Pierre Michel</p>
          <p className="text-xs text-muted-foreground">Engineer · Applied AI · right now</p>
        </div>
      </div>
      <p className="mt-3 text-[13px] text-foreground/85">What I&apos;m shipping at the moment:</p>
      <ul className="mt-2 space-y-1.5">
        {SHIPPING.map((s) => (
          <li key={s.name} className="flex items-center gap-2 text-[13px]">
            <span className="size-1 rounded-full bg-foreground/50" />
            <span className="min-w-0 flex-1 truncate">
              <span className="font-medium">{s.name}</span>
              <span className="text-muted-foreground"> · {s.what}</span>
            </span>
            <span className={cn("inline-flex shrink-0 items-center gap-1 rounded-md px-1.5 py-0.5 text-[11px] font-medium", statusStyle[s.tone])}>
              {s.status === "R&D" ? <RefreshCw className="size-3" /> : s.status === "Leading" ? null : <Check className="size-3" />}
              {s.status}
            </span>
          </li>
        ))}
      </ul>
      <p className="mt-3 text-[13px] text-foreground/85">
        <span className="rounded-md bg-tint-blue px-1.5 py-0.5 font-mono text-[12px] text-ink-blue">@you</span>{" "}
        building something with AI? Let&apos;s talk.
      </p>
    </div>
  );
}

export function HeroIso({ className }: { className?: string }) {
  return (
    <div className={cn("relative", className)}>
      <div className="relative w-full" style={{ aspectRatio: RATIO }}>
        {/* one SVG per theme (walls and floor differ, platform tops are identical) */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src="/illustrations/hero-iso.svg"
          alt="An isometric floor of four platforms: backend, applied AI, frontend and DevOps"
          className="absolute inset-0 size-full select-none dark:hidden"
          draggable={false}
        />
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src="/illustrations/hero-iso-dark.svg"
          alt=""
          aria-hidden="true"
          className="absolute inset-0 hidden size-full select-none dark:block"
          draggable={false}
        />
        <div aria-hidden="true">
          {CHIPS.map((c) => (
            <IconChip key={c.label} chip={c} />
          ))}
          {/* Pierre, on the backend platform */}
          <span
            className="absolute -translate-x-1/2 -translate-y-[85%]"
            style={{ left: `${PIERRE.left}%`, top: `${PIERRE.top}%` }}
          >
            <span className="relative block size-10 overflow-hidden rounded-full shadow-lg ring-2 ring-card sm:size-11">
              <Image src="/images/avatar.png" alt="" fill sizes="44px" className="object-cover" priority />
            </span>
            <span className="absolute -bottom-0.5 -right-0.5 size-3 rounded-full bg-shape-green ring-2 ring-card" />
          </span>
          {/* mono label, like Dust's "@ContentWriter" */}
          <span
            className="absolute -translate-x-1/2 rounded-md border bg-card px-1.5 py-0.5 font-mono text-[10px] text-foreground/80 shadow-sm sm:text-[11px]"
            style={{ left: `${CORTEX.left}%`, top: `${CORTEX.top}%` }}
          >
            @cortex
          </span>
        </div>
      </div>
      <ShippingCard className="animate-float absolute right-[3%] top-[-9%] hidden sm:block" />
    </div>
  );
}
