import { PMMark } from "@/components/site/logo";
import { cn } from "@/lib/utils";

/**
 * Hero illustration (DA v3.3): the whole pipeline, "from scoping to production", as an isometric
 * diorama generated by `scripts/gen-hero-iso.py`: a blueprint and a pencil, a workshop with gears
 * and a smoking chimney, a conveyor of crates to a loading dock and a delivery van, then a rocket on
 * its pad. Four square tags name the stages, and a "currently shipping" card follows the theme.
 * Anchors are the % printed by the generator: re-run it and copy them here if the scene changes.
 */
const RATIO = "629.0 / 433.8";

type Stage = { left: number; top: number; label: string; dot: string };

const STAGES: Stage[] = [
  { left: 20.2, top: 45.1, label: "Scope", dot: "bg-shape-yellow" },
  { left: 40.0, top: 30.9, label: "Build", dot: "bg-shape-blue" },
  { left: 69.3, top: 49.2, label: "Ship", dot: "bg-shape-green" },
  { left: 82.6, top: 58.0, label: "Launch", dot: "bg-shape-red" },
];

/** A stage name above its piece of the scene, tied to it by a hairline. */
function StageTag({ stage, index }: { stage: Stage; index: number }) {
  return (
    <span
      className="absolute hidden -translate-x-1/2 -translate-y-full flex-col items-center sm:flex"
      style={{ left: `${stage.left}%`, top: `${stage.top}%` }}
    >
      <span className="inline-flex items-center gap-1.5 whitespace-nowrap border bg-card px-2 py-1 font-mono text-[10px] uppercase tracking-[0.08em] text-foreground/85 shadow-sm">
        <span className={cn("size-1.5 rounded-full", stage.dot)} />
        <span className="text-muted-foreground">{String(index + 1).padStart(2, "0")}</span>
        {stage.label}
      </span>
      <span className="h-3 w-px bg-foreground/25" />
    </span>
  );
}

// What Pierre ships right now (facts from the case studies; statuses as on the site).
const SHIPPING = [
  { name: "Taskforce", what: "AI delivery OS", status: "Live", tag: "bg-tint-green text-ink-green", dot: "bg-shape-green" },
  { name: "Brain OS", what: "Reference memory", status: "R&D", tag: "bg-tint-blue text-ink-blue", dot: "bg-shape-blue" },
  { name: "Plania", what: "13k-user SaaS", status: "Leading", tag: "bg-tint-yellow text-ink-yellow", dot: "bg-shape-yellow" },
  { name: "Safex", what: "AI sales agent", status: "In production", tag: "bg-tint-green text-ink-green", dot: "bg-shape-green" },
] as const;

/** A square status card in the page's own colours (light in light mode, dark in dark mode). */
function ShippingCard({ className }: { className?: string }) {
  return (
    <div className={cn("w-[21rem] border bg-card text-card-foreground shadow-xl", className)}>
      <div className="flex items-center gap-3 border-b px-4 py-3">
        <PMMark className="h-3.5" />
        <p className="flex-1 text-sm font-semibold tracking-[-0.01em]">Pierre Michel</p>
        <span className="font-mono text-[10px] uppercase tracking-[0.1em] text-muted-foreground">Right now</span>
      </div>
      <ul className="divide-y">
        {SHIPPING.map((s) => (
          <li key={s.name} className="flex items-center gap-3 px-4 py-2.5 text-[13px]">
            <span className="min-w-0 flex-1 truncate">
              <span className="font-medium">{s.name}</span>
              <span className="text-muted-foreground"> · {s.what}</span>
            </span>
            <span className={cn("inline-flex shrink-0 items-center gap-1.5 px-1.5 py-0.5 font-mono text-[10px] uppercase tracking-[0.06em]", s.tag)}>
              <span className={cn("size-1.5 rounded-full", s.dot)} />
              {s.status}
            </span>
          </li>
        ))}
      </ul>
      <p className="flex items-center gap-2 border-t px-4 py-3 text-[13px] text-foreground/85">
        <span className="relative flex size-2">
          <span className="absolute inline-flex size-full animate-pulse-ring rounded-full bg-shape-blue" />
          <span className="relative inline-flex size-2 rounded-full bg-shape-blue" />
        </span>
        Next up: your project?
      </p>
    </div>
  );
}

export function HeroIso({ className }: { className?: string }) {
  return (
    <div className={cn("relative", className)}>
      <div className="relative w-full" style={{ aspectRatio: RATIO }}>
        {/* one SVG per theme (walls, floor and smoke differ, the vivid tops are identical) */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src="/illustrations/hero-iso.svg"
          alt="The product pipeline as a small isometric scene: a blueprint with a pencil, a workshop with gears and a smoking chimney, a conveyor carrying crates to a loading dock and a delivery van, and a rocket on its launch pad"
          className="absolute inset-0 size-full select-none dark:hidden"
          draggable={false}
        />
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src="/illustrations/hero-iso-dark.svg"
          alt=""
          aria-hidden="true"
          className="absolute inset-0 hidden size-full select-none dark:block"
          draggable={false}
        />
        <div aria-hidden="true">
          {STAGES.map((s, i) => (
            <StageTag key={s.label} stage={s} index={i} />
          ))}
        </div>
      </div>
      {/* only where the column is wide enough not to cover the scene (a bit smaller below 1440px) */}
      <ShippingCard className="animate-float absolute right-8 hidden origin-top-right xl:top-[-29%] xl:block xl:scale-[0.88] min-[90rem]:top-[-25%] min-[90rem]:scale-100" />
    </div>
  );
}
