import Image from "next/image";
import { Layers, Rocket, Sparkles, type LucideIcon } from "lucide-react";
import { PMMark } from "@/components/site/logo";
import { cn } from "@/lib/utils";

/**
 * Hero illustration (DA v3.2): abstract isometric building blocks generated by
 * `scripts/gen-hero-iso.py` (a staircase climbing to a cobalt block, a pink tower, a lime round
 * tower, a green slab), a few round icon chips, Pierre on top, and a "currently shipping" card
 * that follows the theme. Anchors are the % printed by the generator: re-run it and copy them here
 * if the scene changes.
 */
const RATIO = "872.2 / 552";

type Chip = { left: number; top: number; icon: LucideIcon; label: string };

const CHIPS: Chip[] = [
  { left: 67.9, top: 40.6, icon: Sparkles, label: "Applied AI" },
  { left: 38.1, top: 41.7, icon: Layers, label: "Products" },
  { left: 47.6, top: 74.3, icon: Rocket, label: "Shipped" },
];
const PIERRE = { left: 47.6, top: 37.3 };

function IconChip({ chip }: { chip: Chip }) {
  const Icon = chip.icon;
  return (
    <span
      className="absolute grid size-8 -translate-x-1/2 -translate-y-[90%] place-items-center rounded-full border border-foreground/10 bg-card text-foreground/80 shadow-md sm:size-9"
      style={{ left: `${chip.left}%`, top: `${chip.top}%` }}
      title={chip.label}
    >
      <Icon className="size-3.5 sm:size-4" strokeWidth={1.75} />
    </span>
  );
}

// What Pierre ships right now (facts from the case studies; statuses as on the site).
const SHIPPING = [
  { name: "Taskforce", what: "AI delivery OS", status: "Live", tag: "bg-tint-green text-ink-green", dot: "bg-shape-green" },
  { name: "Brain OS", what: "Reference memory", status: "R&D", tag: "bg-tint-blue text-ink-blue", dot: "bg-shape-blue" },
  { name: "Plania", what: "13k-user SaaS", status: "Leading", tag: "bg-tint-yellow text-ink-yellow", dot: "bg-shape-yellow" },
  { name: "Safex", what: "AI sales agent", status: "In production", tag: "bg-tint-green text-ink-green", dot: "bg-shape-green" },
] as const;

/** A square status card in the page's own colours (light in light mode, dark in dark mode). */
function ShippingCard({ className }: { className?: string }) {
  return (
    <div className={cn("w-[21rem] border bg-card text-card-foreground shadow-xl", className)}>
      <div className="flex items-center gap-3 border-b px-4 py-3">
        <PMMark className="h-3.5" />
        <p className="flex-1 text-sm font-semibold tracking-[-0.01em]">Pierre Michel</p>
        <span className="font-mono text-[10px] uppercase tracking-[0.1em] text-muted-foreground">Right now</span>
      </div>
      <ul className="divide-y">
        {SHIPPING.map((s) => (
          <li key={s.name} className="flex items-center gap-3 px-4 py-2.5 text-[13px]">
            <span className="min-w-0 flex-1 truncate">
              <span className="font-medium">{s.name}</span>
              <span className="text-muted-foreground"> · {s.what}</span>
            </span>
            <span className={cn("inline-flex shrink-0 items-center gap-1.5 px-1.5 py-0.5 font-mono text-[10px] uppercase tracking-[0.06em]", s.tag)}>
              <span className={cn("size-1.5 rounded-full", s.dot)} />
              {s.status}
            </span>
          </li>
        ))}
      </ul>
      <p className="flex items-center gap-2 border-t px-4 py-3 text-[13px] text-foreground/85">
        <span className="relative flex size-2">
          <span className="absolute inline-flex size-full animate-pulse-ring rounded-full bg-shape-blue" />
          <span className="relative inline-flex size-2 rounded-full bg-shape-blue" />
        </span>
        Next up: your project?
      </p>
    </div>
  );
}

export function HeroIso({ className }: { className?: string }) {
  return (
    <div className={cn("relative", className)}>
      <div className="relative w-full" style={{ aspectRatio: RATIO }}>
        {/* one SVG per theme (walls and floor differ, block tops are identical) */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src="/illustrations/hero-iso.svg"
          alt="Isometric building blocks: a staircase climbing to a blue block with a pink tower, a round lime tower and a few slabs"
          className="absolute inset-0 size-full select-none dark:hidden"
          draggable={false}
        />
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src="/illustrations/hero-iso-dark.svg"
          alt=""
          aria-hidden="true"
          className="absolute inset-0 hidden size-full select-none dark:block"
          draggable={false}
        />
        <div aria-hidden="true">
          {CHIPS.map((c) => (
            <IconChip key={c.label} chip={c} />
          ))}
          {/* Pierre, on top of the pink tower */}
          <span className="absolute -translate-x-1/2 -translate-y-[88%]" style={{ left: `${PIERRE.left}%`, top: `${PIERRE.top}%` }}>
            <span className="relative block size-9 overflow-hidden rounded-full border-2 border-card shadow-lg sm:size-11">
              <Image src="/images/avatar.png" alt="" fill sizes="44px" className="object-cover" priority />
            </span>
            <span className="absolute bottom-0 right-0 size-3 rounded-full border-2 border-card bg-shape-green" />
          </span>
        </div>
      </div>
      {/* only where the column is wide enough not to cover the blocks (a bit smaller below 1440px) */}
      <ShippingCard className="animate-float absolute right-8 hidden origin-top-right xl:top-[-33%] xl:block xl:scale-[0.88] min-[1440px]:top-[-28%] min-[1440px]:scale-100" />
    </div>
  );
}
